name: expose
description: A two hour exercise, based on the Risk game, to learn Polymer.dart.
dependencies:
  browser: any
  polymer: '>=0.12.0 <0.13.0'
dev_dependencies:
  mock: any
  unittest: any
transformers:
- polymer:
    entry_points: web/index.html
